---
language: ruby
script: "bundle exec $TESTCOMMAND"
rvm:
  - 1.9.3
  - 2.1.1
  - rbx-2
  - rbx
  - jruby
env:
  - TESTCOMMAND="qed"
  - TESTCOMMAND="rubytest -Ilib -Itest test/"
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: rbx-2
cache: bundler
